//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.WebUI.Xaml {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.WebUI.Xaml.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account name 的本地化字符串。
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account name or email address 的本地化字符串。
        /// </summary>
        internal static string AccountNameOrEmailAddress {
            get {
                return ResourceManager.GetString("AccountNameOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account status 的本地化字符串。
        /// </summary>
        internal static string AccountStatus {
            get {
                return ResourceManager.GetString("AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add accounts 的本地化字符串。
        /// </summary>
        internal static string AddAccounts {
            get {
                return ResourceManager.GetString("AddAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add features 的本地化字符串。
        /// </summary>
        internal static string AddFeatures {
            get {
                return ResourceManager.GetString("AddFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add roles 的本地化字符串。
        /// </summary>
        internal static string AddRoles {
            get {
                return ResourceManager.GetString("AddRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign permissions 的本地化字符串。
        /// </summary>
        internal static string AssignPermissions {
            get {
                return ResourceManager.GetString("AssignPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign roles 的本地化字符串。
        /// </summary>
        internal static string AssignRoles {
            get {
                return ResourceManager.GetString("AssignRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch deletion 的本地化字符串。
        /// </summary>
        internal static string BatchDeletion {
            get {
                return ResourceManager.GetString("BatchDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change login password 的本地化字符串。
        /// </summary>
        internal static string ChangeLoginPassword {
            get {
                return ResourceManager.GetString("ChangeLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change password 的本地化字符串。
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm choice 的本地化字符串。
        /// </summary>
        internal static string ConfirmChoice {
            get {
                return ResourceManager.GetString("ConfirmChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm password 的本地化字符串。
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm submission 的本地化字符串。
        /// </summary>
        internal static string ConfirmSubmission {
            get {
                return ResourceManager.GetString("ConfirmSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit function - {0} 的本地化字符串。
        /// </summary>
        internal static string EditFunction {
            get {
                return ResourceManager.GetString("EditFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit role - {0} 的本地化字符串。
        /// </summary>
        internal static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email address 的本地化字符串。
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in the function of the realized function of the site, so that they can be assigned to the related menus and roles, so as to achieve the purpose of using the account of different identities for different purposes 的本地化字符串。
        /// </summary>
        internal static string FDTip {
            get {
                return ResourceManager.GetString("FDTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function name 的本地化字符串。
        /// </summary>
        internal static string FunctionName {
            get {
                return ResourceManager.GetString("FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gender 的本地化字符串。
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identification code 的本地化字符串。
        /// </summary>
        internal static string IdentificationCode {
            get {
                return ResourceManager.GetString("IdentificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information authentication 的本地化字符串。
        /// </summary>
        internal static string InformationAuthentication {
            get {
                return ResourceManager.GetString("InformationAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of existing accounts 的本地化字符串。
        /// </summary>
        internal static string ListOfExistingAccounts {
            get {
                return ResourceManager.GetString("ListOfExistingAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login IP 的本地化字符串。
        /// </summary>
        internal static string LoginIP {
            get {
                return ResourceManager.GetString("LoginIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login name 的本地化字符串。
        /// </summary>
        internal static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For your account security, please fill in the login name 的本地化字符串。
        /// </summary>
        internal static string LoginNameTip {
            get {
                return ResourceManager.GetString("LoginNameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login password 的本地化字符串。
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login time 的本地化字符串。
        /// </summary>
        internal static string LoginTime {
            get {
                return ResourceManager.GetString("LoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login times 的本地化字符串。
        /// </summary>
        internal static string LoginTimes {
            get {
                return ResourceManager.GetString("LoginTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify account information 的本地化字符串。
        /// </summary>
        internal static string ModifyAccountInformation {
            get {
                return ResourceManager.GetString("ModifyAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModifyAccountInformation - {0} 的本地化字符串。
        /// </summary>
        internal static string ModifyAccountInformationTip {
            get {
                return ResourceManager.GetString("ModifyAccountInformationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify function 的本地化字符串。
        /// </summary>
        internal static string ModifyFunction {
            get {
                return ResourceManager.GetString("ModifyFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify role 的本地化字符串。
        /// </summary>
        internal static string ModifyRole {
            get {
                return ResourceManager.GetString("ModifyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My profile 的本地化字符串。
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New password 的本地化字符串。
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original password 的本地化字符串。
        /// </summary>
        internal static string OriginalPassword {
            get {
                return ResourceManager.GetString("OriginalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For your account security, please fill in the original password 的本地化字符串。
        /// </summary>
        internal static string PasswordTip {
            get {
                return ResourceManager.GetString("PasswordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can use this email to reset your password if you forget your password 的本地化字符串。
        /// </summary>
        internal static string PasswordTip1 {
            get {
                return ResourceManager.GetString("PasswordTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password entered twice is different 的本地化字符串。
        /// </summary>
        internal static string PasswordTip2 {
            get {
                return ResourceManager.GetString("PasswordTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your password again 的本地化字符串。
        /// </summary>
        internal static string PasswordTip3 {
            get {
                return ResourceManager.GetString("PasswordTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personal information 的本地化字符串。
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo 的本地化字符串。
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The volume of the photo is within 2M, and the height and width are 190*190 的本地化字符串。
        /// </summary>
        internal static string PhotoRequirements {
            get {
                return ResourceManager.GetString("PhotoRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regular role 的本地化字符串。
        /// </summary>
        internal static string RegularRole {
            get {
                return ResourceManager.GetString("RegularRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role name 的本地化字符串。
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can assign functions to the role that you can use, and these functions belong to a menu, so different roles can be accessed by different menus 的本地化字符串。
        /// </summary>
        internal static string RoleTip {
            get {
                return ResourceManager.GetString("RoleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role type 的本地化字符串。
        /// </summary>
        internal static string RoleType {
            get {
                return ResourceManager.GetString("RoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved successfully 的本地化字符串。
        /// </summary>
        internal static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site function list 的本地化字符串。
        /// </summary>
        internal static string SiteFunctionList {
            get {
                return ResourceManager.GetString("SiteFunctionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site role list 的本地化字符串。
        /// </summary>
        internal static string SiteRoleList {
            get {
                return ResourceManager.GetString("SiteRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful operation 的本地化字符串。
        /// </summary>
        internal static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System role 的本地化字符串。
        /// </summary>
        internal static string SystemRole {
            get {
                return ResourceManager.GetString("SystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telephone number 的本地化字符串。
        /// </summary>
        internal static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot complete the upload operation without specifying the virtual directory number where the file is located 的本地化字符串。
        /// </summary>
        internal static string UploadNoDirectory {
            get {
                return ResourceManager.GetString("UploadNoDirectory", resourceCulture);
            }
        }
    }
}
