//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeArt.DomainDriven {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeArt.DomainDriven.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Called by the caller to perform domain event back operations 的本地化字符串。
        /// </summary>
        internal static string AskedToReverseTip {
            get {
                return ResourceManager.GetString("AskedToReverseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of BearValue can not be obtained because there is no value 的本地化字符串。
        /// </summary>
        internal static string BearNoValue {
            get {
                return ResourceManager.GetString("BearNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not add a mirror during transaction commits 的本地化字符串。
        /// </summary>
        internal static string CanNotAddMirror {
            get {
                return ResourceManager.GetString("CanNotAddMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can only include {1} 的本地化字符串。
        /// </summary>
        internal static string CanOnlyInclude {
            get {
                return ResourceManager.GetString("CanOnlyInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese, English letters 的本地化字符串。
        /// </summary>
        internal static string CE {
            get {
                return ResourceManager.GetString("CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese, English letters, numbers 的本地化字符串。
        /// </summary>
        internal static string CEN {
            get {
                return ResourceManager.GetString("CEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese, numbers 的本地化字符串。
        /// </summary>
        internal static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is a local event and can not participate in the Continue operation 的本地化字符串。
        /// </summary>
        internal static string ContinueNotWithLocal {
            get {
                return ResourceManager.GetString("ContinueNotWithLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 queue {0} event {1} is not a Rasing state and can not participate in the Continue operation 的本地化字符串。
        /// </summary>
        internal static string ContinueWithNotRaising {
            get {
                return ResourceManager.GetString("ContinueWithNotRaising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data version error, modified failed,type {0} id {1} 的本地化字符串。
        /// </summary>
        internal static string DataVersionError {
            get {
                return ResourceManager.GetString("DataVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} does not meet the rules {1} 的本地化字符串。
        /// </summary>
        internal static string DoesNotMeetRule {
            get {
                return ResourceManager.GetString("DoesNotMeetRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DomainBuffer.Mirror is null, you can not use the mirror buffer 的本地化字符串。
        /// </summary>
        internal static string DomainBufferMirrorNull {
            get {
                return ResourceManager.GetString("DomainBufferMirrorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain Property {0} has been removed 的本地化字符串。
        /// </summary>
        internal static string DomainPropertyRemoved {
            get {
                return ResourceManager.GetString("DomainPropertyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Do not meet the specifications 的本地化字符串。
        /// </summary>
        internal static string DoNotMeetSpecifications {
            get {
                return ResourceManager.GetString("DoNotMeetSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The dto data is malformed and does not match the definition {0} 的本地化字符串。
        /// </summary>
        internal static string DynamicObjectLoadError {
            get {
                return ResourceManager.GetString("DynamicObjectLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defines multiple dynamic types with the name {0} 的本地化字符串。
        /// </summary>
        internal static string DynamicTypeRepeated {
            get {
                return ResourceManager.GetString("DynamicTypeRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty object {0} are read-only 的本地化字符串。
        /// </summary>
        internal static string EmptyReadOnly {
            get {
                return ResourceManager.GetString("EmptyReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English letters, numbers 的本地化字符串。
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In queue {0}, the event entry {1} was not found and the callback result operation after remote event execution could not be completed 的本地化字符串。
        /// </summary>
        internal static string EventEntryNotExistWithCallbackTip {
            get {
                return ResourceManager.GetString("EventEntryNotExistWithCallbackTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during the execution of a domain event, but it has been restored 的本地化字符串。
        /// </summary>
        internal static string EventErrorAndRestored {
            get {
                return ResourceManager.GetString("EventErrorAndRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during the execution of the domain event and there was no successful recovery. This is a serious exception. 的本地化字符串。
        /// </summary>
        internal static string EventErrotTip {
            get {
                return ResourceManager.GetString("EventErrotTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event {0} was not triggered 的本地化字符串。
        /// </summary>
        internal static string EventNotTriggered {
            get {
                return ResourceManager.GetString("EventNotTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The event queue is already open 的本地化字符串。
        /// </summary>
        internal static string EventQueueOpened {
            get {
                return ResourceManager.GetString("EventQueueOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event {0} has been reversed 的本地化字符串。
        /// </summary>
        internal static string EventReversed {
            get {
                return ResourceManager.GetString("EventReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event {0} has been triggered 的本地化字符串。
        /// </summary>
        internal static string EventTriggered {
            get {
                return ResourceManager.GetString("EventTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while executing 的本地化字符串。
        /// </summary>
        internal static string ExecuteError {
            get {
                return ResourceManager.GetString("ExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute remote event {0} timeout 的本地化字符串。
        /// </summary>
        internal static string ExecuteRemoteEventTimeout {
            get {
                return ResourceManager.GetString("ExecuteRemoteEventTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obtain an unexpected error in getting system service {0} 的本地化字符串。
        /// </summary>
        internal static string GetServiceUnexpectedError {
            get {
                return ResourceManager.GetString("GetServiceUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to compute the unique key for type {0}, which must be IAggregateRoot  的本地化字符串。
        /// </summary>
        internal static string GetUniqueKeyError {
            get {
                return ResourceManager.GetString("GetUniqueKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field events cannot be completed due to a power failure or hardware failure 的本地化字符串。
        /// </summary>
        internal static string HardwareFailureTip {
            get {
                return ResourceManager.GetString("HardwareFailureTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0} is incorrect for the email format 的本地化字符串。
        /// </summary>
        internal static string IncorrectEmailFormat {
            get {
                return ResourceManager.GetString("IncorrectEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is incorrect for the mobile number format 的本地化字符串。
        /// </summary>
        internal static string IncorrectMobileNumberFormat {
            get {
                return ResourceManager.GetString("IncorrectMobileNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In the domain design, all objects should not be null, the source of the error: {0} 的本地化字符串。
        /// </summary>
        internal static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} count less than {1} 的本地化字符串。
        /// </summary>
        internal static string ListCountLessThan {
            get {
                return ResourceManager.GetString("ListCountLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} count more than {1} 的本地化字符串。
        /// </summary>
        internal static string ListCountMoreThan {
            get {
                return ResourceManager.GetString("ListCountMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list {0} validation error {1} 的本地化字符串。
        /// </summary>
        internal static string ListItemError {
            get {
                return ResourceManager.GetString("ListItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock operation does not allow the use of the QueryLevel.None level 的本地化字符串。
        /// </summary>
        internal static string LockLevelError {
            get {
                return ResourceManager.GetString("LockLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The metadata code for type {0} is different. In dynamic class, the metadataCode of the same type name is the same 的本地化字符串。
        /// </summary>
        internal static string MetadataCodeError {
            get {
                return ResourceManager.GetString("MetadataCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The domain derived class {0} must specify a unique typeKey 的本地化字符串。
        /// </summary>
        internal static string NeedTypeKey {
            get {
                return ResourceManager.GetString("NeedTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no data context, please check whether it is in command mode or manually open the data context 的本地化字符串。
        /// </summary>
        internal static string NoDataContext {
            get {
                return ResourceManager.GetString("NoDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} does not define empty, we agree that each field type will have a static property of Empty, representing an empty object 的本地化字符串。
        /// </summary>
        internal static string NoDefineEmpty {
            get {
                return ResourceManager.GetString("NoDefineEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warehouse {0} does not define a static method for loading warehouse construct parameter {1} 的本地化字符串。
        /// </summary>
        internal static string NoDefineLoadConstructParameter {
            get {
                return ResourceManager.GetString("NoDefineLoadConstructParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository {0} does not define method {1} 的本地化字符串。
        /// </summary>
        internal static string NoDefineMethodFromRepository {
            get {
                return ResourceManager.GetString("NoDefineMethodFromRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No definition of property {1} found in type {0} 的本地化字符串。
        /// </summary>
        internal static string NoDefinitionProperty {
            get {
                return ResourceManager.GetString("NoDefinitionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No dynamic type definition found for {0} 的本地化字符串。
        /// </summary>
        internal static string NoDyanmicTypeDefine {
            get {
                return ResourceManager.GetString("NoDyanmicTypeDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not find the remote type {0} in the local dynamic type definition 的本地化字符串。
        /// </summary>
        internal static string NoDyanmicTypeDefineForRemoteType {
            get {
                return ResourceManager.GetString("NoDyanmicTypeDefineForRemoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The definition of event {0} was not found 的本地化字符串。
        /// </summary>
        internal static string NoEvent {
            get {
                return ResourceManager.GetString("NoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} does not define event attribute 的本地化字符串。
        /// </summary>
        internal static string NoEventAttribute {
            get {
                return ResourceManager.GetString("NoEventAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No event definitions for type {0} were found 的本地化字符串。
        /// </summary>
        internal static string NoFoundEventTip {
            get {
                return ResourceManager.GetString("NoFoundEventTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No {1} object found with id {0} 的本地化字符串。
        /// </summary>
        internal static string NoObjectById {
            get {
                return ResourceManager.GetString("NoObjectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} is no definition of the repository constructor 的本地化字符串。
        /// </summary>
        internal static string NoRepositoryConstructor {
            get {
                return ResourceManager.GetString("NoRepositoryConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} not ascii 的本地化字符串。
        /// </summary>
        internal static string NotASCII {
            get {
                return ResourceManager.GetString("NotASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} does not define ObjectRepositoryAttribute 的本地化字符串。
        /// </summary>
        internal static string NotDefinedObjectRepositoryAttribute {
            get {
                return ResourceManager.GetString("NotDefinedObjectRepositoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property {0} can not be empty 的本地化字符串。
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ILockManager implementation is not configured and the object can not be locked 的本地化字符串。
        /// </summary>
        internal static string NotExistLockManager {
            get {
                return ResourceManager.GetString("NotExistLockManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not find {0} the domain derived class type 的本地化字符串。
        /// </summary>
        internal static string NotFoundDerivedType {
            get {
                return ResourceManager.GetString("NotFoundDerivedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} does not define Empty static property or does not assign value to Empty static property 的本地化字符串。
        /// </summary>
        internal static string NotFoundEmpty {
            get {
                return ResourceManager.GetString("NotFoundEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No event entry with queue id {0} event id {1} was found 的本地化字符串。
        /// </summary>
        internal static string NotFoundEventEntry {
            get {
                return ResourceManager.GetString("NotFoundEventEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not find the {0} {1} remotable definition 的本地化字符串。
        /// </summary>
        internal static string NotFoundRemotable {
            get {
                return ResourceManager.GetString("NotFoundRemotable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not find the implementation of {0} repository 的本地化字符串。
        /// </summary>
        internal static string NotFoundRepository {
            get {
                return ResourceManager.GetString("NotFoundRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} did not implement {1} method 的本地化字符串。
        /// </summary>
        internal static string NotImplementedMethod {
            get {
                return ResourceManager.GetString("NotImplementedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object does not include the actual value and can not get the actual value of the nullable type 的本地化字符串。
        /// </summary>
        internal static string NotIncludeValue {
            get {
                return ResourceManager.GetString("NotIncludeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not open the transaction 的本地化字符串。
        /// </summary>
        internal static string NotOpenTransaction {
            get {
                return ResourceManager.GetString("NotOpenTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} property {1} does not mark PropertyRepository attribute, all domain properties should be able to be added to the warehouse 的本地化字符串。
        /// </summary>
        internal static string NotPropertyRepository {
            get {
                return ResourceManager.GetString("NotPropertyRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} error, the first argument to the ObjectExtensionAttribute must be a field object type or a domain object extension class 的本地化字符串。
        /// </summary>
        internal static string ObjectExtensionAttributeFirstParamError {
            get {
                return ResourceManager.GetString("ObjectExtensionAttributeFirstParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} error,You can only persist IAggregateRoot or IEntityObjectPro objects 的本地化字符串。
        /// </summary>
        internal static string PersistTargetTypeError {
            get {
                return ResourceManager.GetString("PersistTargetTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method {0} does not meet the requirements, the domain property action must be static on the domain object extension class 的本地化字符串。
        /// </summary>
        internal static string PropertyActionObjectExtensionNoStatic {
            get {
                return ResourceManager.GetString("PropertyActionObjectExtensionNoStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} does not meet the requirements, static domain property action must be defined in the domain object extension class members 的本地化字符串。
        /// </summary>
        internal static string PropertyActionObjectExtensionTypeError {
            get {
                return ResourceManager.GetString("PropertyActionObjectExtensionTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} does not meet the requirements, non-static domain property action must be defined in the domain object class members 的本地化字符串。
        /// </summary>
        internal static string PropertyActionObjectTypeError {
            get {
                return ResourceManager.GetString("PropertyActionObjectTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of property {0} is repeated 的本地化字符串。
        /// </summary>
        internal static string PropertyValueRepeated {
            get {
                return ResourceManager.GetString("PropertyValueRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue {0} does not exist and cannot complete callback result operations after remote event execution 的本地化字符串。
        /// </summary>
        internal static string QueueNotExistWithCallbackTip {
            get {
                return ResourceManager.GetString("QueueNotExistWithCallbackTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recovery domain event failed,  queue id {0} 的本地化字符串。
        /// </summary>
        internal static string RecoveryEventFailed {
            get {
                return ResourceManager.GetString("RecoveryEventFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} repeatedly defined property {1} 的本地化字符串。
        /// </summary>
        internal static string RepeatedDeclareProperty {
            get {
                return ResourceManager.GetString("RepeatedDeclareProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception in return data context, Borrowcount greater than 0 的本地化字符串。
        /// </summary>
        internal static string ReturnDataContextError {
            get {
                return ResourceManager.GetString("ReturnDataContextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} object snapshots are read-only 的本地化字符串。
        /// </summary>
        internal static string SnapshotReadOnly {
            get {
                return ResourceManager.GetString("SnapshotReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only create an object snapshot for AggregateRoot 的本地化字符串。
        /// </summary>
        internal static string SnapshotTargetError {
            get {
                return ResourceManager.GetString("SnapshotTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} length less than {1} 的本地化字符串。
        /// </summary>
        internal static string StringLengthLessThan {
            get {
                return ResourceManager.GetString("StringLengthLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} length more than {1} 的本地化字符串。
        /// </summary>
        internal static string StringLengthMoreThan {
            get {
                return ResourceManager.GetString("StringLengthMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transaction has entered the commit phase and can not be submitted repeatedly! 的本地化字符串。
        /// </summary>
        internal static string TransactionRepeatedCommit {
            get {
                return ResourceManager.GetString("TransactionRepeatedCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown type {0} 的本地化字符串。
        /// </summary>
        internal static string TypeDefineFindTypeError {
            get {
                return ResourceManager.GetString("TypeDefineFindTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninitialized domain object 的本地化字符串。
        /// </summary>
        internal static string UninitializedDomainObject {
            get {
                return ResourceManager.GetString("UninitializedDomainObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized dynamic type {0} 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedType {
            get {
                return ResourceManager.GetString("UnrecognizedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} value less than {1} 的本地化字符串。
        /// </summary>
        internal static string ValueLessThan {
            get {
                return ResourceManager.GetString("ValueLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} value more than {1} 的本地化字符串。
        /// </summary>
        internal static string ValueMoreThan {
            get {
                return ResourceManager.GetString("ValueMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ValueObject {0} is read-only 的本地化字符串。
        /// </summary>
        internal static string ValueObjectReadOnly {
            get {
                return ResourceManager.GetString("ValueObjectReadOnly", resourceCulture);
            }
        }
    }
}
