//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeArt {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeArt.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} out of range 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item is not lent and cannot be returned to the pool 的本地化字符串。
        /// </summary>
        internal static string CannotReturnPoolItem {
            get {
                return ResourceManager.GetString("CannotReturnPoolItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile error 的本地化字符串。
        /// </summary>
        internal static string CompileError {
            get {
                return ResourceManager.GetString("CompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard and release items in the pool failed, the error occurred in a {0} instance 的本地化字符串。
        /// </summary>
        internal static string DisposePoolItemFailed {
            get {
                return ResourceManager.GetString("DisposePoolItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There can be only one member definition for a collection {0} 的本地化字符串。
        /// </summary>
        internal static string DTOListTypeCountError {
            get {
                return ResourceManager.GetString("DTOListTypeCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry {0} does not specify type information 的本地化字符串。
        /// </summary>
        internal static string DTONotSpecifyType {
            get {
                return ResourceManager.GetString("DTONotSpecifyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation can not be performed in read-only mode 的本地化字符串。
        /// </summary>
        internal static string DTOReadOnly {
            get {
                return ResourceManager.GetString("DTOReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In the completion method, you can not specify that the status is not completed (Incomplete) 的本地化字符串。
        /// </summary>
        internal static string FutureCompleteError {
            get {
                return ResourceManager.GetString("FutureCompleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The result is not valid because the future &lt;{0}&gt; instance has been canceled 的本地化字符串。
        /// </summary>
        internal static string FutureResultNotValid {
            get {
                return ResourceManager.GetString("FutureResultNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid timing time, beyond the scope of system support 的本地化字符串。
        /// </summary>
        internal static string InvalidPeriod {
            get {
                return ResourceManager.GetString("InvalidPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not set the implementation of AppSession, can not use the application to answer 的本地化字符串。
        /// </summary>
        internal static string NoAppSession {
            get {
                return ResourceManager.GetString("NoAppSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} node, there is no {1} attribute defined 的本地化字符串。
        /// </summary>
        internal static string NodeNoAttribute {
            get {
                return ResourceManager.GetString("NodeNoAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no implementation of interface {0} that can not get an instance 的本地化字符串。
        /// </summary>
        internal static string NoInterfaceImpl {
            get {
                return ResourceManager.GetString("NoInterfaceImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property {0} is not defined on type {1} 的本地化字符串。
        /// </summary>
        internal static string NoPropertyDefined {
            get {
                return ResourceManager.GetString("NoPropertyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no symbiosis, please check whether manually open the symbiosis 的本地化字符串。
        /// </summary>
        internal static string NoSymbiosis {
            get {
                return ResourceManager.GetString("NoSymbiosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} did not find the corresponding item pool 的本地化字符串。
        /// </summary>
        internal static string NotFoundPoolItem {
            get {
                return ResourceManager.GetString("NotFoundPoolItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No information for tenant {0} was found 的本地化字符串。
        /// </summary>
        internal static string NotFoundTenant {
            get {
                return ResourceManager.GetString("NotFoundTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PoolFetchOrder {0} is not supported 的本地化字符串。
        /// </summary>
        internal static string NotSupportedPoolFetchOrder {
            get {
                return ResourceManager.GetString("NotSupportedPoolFetchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No type {0} defined 的本地化字符串。
        /// </summary>
        internal static string NoTypeDefined {
            get {
                return ResourceManager.GetString("NoTypeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support type {0} only 的本地化字符串。
        /// </summary>
        internal static string OnlySupportedTypes {
            get {
                return ResourceManager.GetString("OnlySupportedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item in the pool has been lent. This error indicates that the pool frame has a BUG, otherwise the error will not occur 的本地化字符串。
        /// </summary>
        internal static string PoolItemHaveBeenLent {
            get {
                return ResourceManager.GetString("PoolItemHaveBeenLent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreApplicationEndAttribute call method {0}. {1} must be static 的本地化字符串。
        /// </summary>
        internal static string PreApplicationEndNoStatic {
            get {
                return ResourceManager.GetString("PreApplicationEndNoStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreApplicationStartAttribute call method {0}. {1} must be static 的本地化字符串。
        /// </summary>
        internal static string PreApplicationStartNoStatic {
            get {
                return ResourceManager.GetString("PreApplicationStartNoStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProApplicationStartedAttribute call method {0}. {1} must be static 的本地化字符串。
        /// </summary>
        internal static string ProApplicationStartedNoStatic {
            get {
                return ResourceManager.GetString("ProApplicationStartedNoStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item has been loaned and cannot be lent again. This means that the {0} framework has BUG, please check the reason 的本地化字符串。
        /// </summary>
        internal static string RepeatBorrowingPoolItem {
            get {
                return ResourceManager.GetString("RepeatBorrowingPoolItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform expression error 的本地化字符串。
        /// </summary>
        internal static string TransformExpressionError {
            get {
                return ResourceManager.GetString("TransformExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0}| mismatch type: {1} 的本地化字符串。
        /// </summary>
        internal static string TypeMismatch {
            get {
                return ResourceManager.GetString("TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} is not appSession access or does not set AppSessionAccessAttribute 的本地化字符串。
        /// </summary>
        internal static string TypeUnAppSessionAccess {
            get {
                return ResourceManager.GetString("TypeUnAppSessionAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} is not concurrent access safe or does not set SafeAccessAttribute 的本地化字符串。
        /// </summary>
        internal static string TypeUnsafeConcurrentAccess {
            get {
                return ResourceManager.GetString("TypeUnsafeConcurrentAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable start media timer 的本地化字符串。
        /// </summary>
        internal static string UnableStartMediaTimer {
            get {
                return ResourceManager.GetString("UnableStartMediaTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown error occurred 的本地化字符串。
        /// </summary>
        internal static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
    }
}
