//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeArt.WPF.Controls.Playstation {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeArt.WPF.Controls.Playstation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can not be less than {1} characters 的本地化字符串。
        /// </summary>
        public static string CanNotBeLessCharacters {
            get {
                return ResourceManager.GetString("CanNotBeLessCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can not be less than {1} items 的本地化字符串。
        /// </summary>
        public static string CanNotBeLessItems {
            get {
                return ResourceManager.GetString("CanNotBeLessItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can not be longer than {1} characters 的本地化字符串。
        /// </summary>
        public static string CanNotBeLongerCharacters {
            get {
                return ResourceManager.GetString("CanNotBeLongerCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can not be more than {1} 的本地化字符串。
        /// </summary>
        public static string CanNotBeMoreItems {
            get {
                return ResourceManager.GetString("CanNotBeMoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not disable the currently used view 的本地化字符串。
        /// </summary>
        public static string CanNotDisableUsedView {
            get {
                return ResourceManager.GetString("CanNotDisableUsedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can only have up to {1} 的本地化字符串。
        /// </summary>
        public static string CanOnlyUp {
            get {
                return ResourceManager.GetString("CanOnlyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 file 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScreenKeyboard 的本地化字符串。
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New item 的本地化字符串。
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data 的本地化字符串。
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No desktop button named {0} was found 的本地化字符串。
        /// </summary>
        public static string NoDesktopButton {
            get {
                return ResourceManager.GetString("NoDesktopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No item with Value {0} found 的本地化字符串。
        /// </summary>
        public static string NoItemWithValue {
            get {
                return ResourceManager.GetString("NoItemWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not find the view {0} 的本地化字符串。
        /// </summary>
        public static string NotFoundView {
            get {
                return ResourceManager.GetString("NotFoundView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please enter 的本地化字符串。
        /// </summary>
        public static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please initialize before using the Items component 的本地化字符串。
        /// </summary>
        public static string PleaseInitializeItemsComponent {
            get {
                return ResourceManager.GetString("PleaseInitializeItemsComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the file 的本地化字符串。
        /// </summary>
        public static string PleaseSelectFile {
            get {
                return ResourceManager.GetString("PleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please upload 的本地化字符串。
        /// </summary>
        public static string PleaseUpload {
            get {
                return ResourceManager.GetString("PleaseUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait 的本地化字符串。
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing request 的本地化字符串。
        /// </summary>
        public static string ProcessingRequest {
            get {
                return ResourceManager.GetString("ProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful operation 的本地化字符串。
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System prompt 的本地化字符串。
        /// </summary>
        public static string SystemPrompt {
            get {
                return ResourceManager.GetString("SystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UploadAction is not set, you can not use the Upload component 的本地化字符串。
        /// </summary>
        public static string UploadActionNotSet {
            get {
                return ResourceManager.GetString("UploadActionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading files 的本地化字符串。
        /// </summary>
        public static string UploadingFiles {
            get {
                return ResourceManager.GetString("UploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please upload {0} or wait for the {0} upload to finish before submitting 的本地化字符串。
        /// </summary>
        public static string WaitUpload {
            get {
                return ResourceManager.GetString("WaitUpload", resourceCulture);
            }
        }
    }
}
