//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeArt.Net.Anycast {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeArt.Net.Anycast.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Channel already exists on address {0} 的本地化字符串。
        /// </summary>
        internal static string ChannelExistsOnAddress {
            get {
                return ResourceManager.GetString("ChannelExistsOnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} no channel, can not use the ability object 的本地化字符串。
        /// </summary>
        internal static string ChannelExistsOnCapability {
            get {
                return ResourceManager.GetString("ChannelExistsOnCapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error connecting to the server 的本地化字符串。
        /// </summary>
        internal static string ConnectServerError {
            get {
                return ResourceManager.GetString("ConnectServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has been added to the channel 的本地化字符串。
        /// </summary>
        internal static string HasJoinedChannel {
            get {
                return ResourceManager.GetString("HasJoinedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No ability to find {0} in context 的本地化字符串。
        /// </summary>
        internal static string NoCapabilityAtContext {
            get {
                return ResourceManager.GetString("NoCapabilityAtContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No channel was created at address {0} 的本地化字符串。
        /// </summary>
        internal static string NoChannelCreatedAtAddress {
            get {
                return ResourceManager.GetString("NoChannelCreatedAtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not connected to the server 的本地化字符串。
        /// </summary>
        internal static string NotConnectedServer {
            get {
                return ResourceManager.GetString("NotConnectedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeated many times after the failure 的本地化字符串。
        /// </summary>
        internal static string ReconnectFailedError {
            get {
                return ResourceManager.GetString("ReconnectFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error running the server 的本地化字符串。
        /// </summary>
        internal static string RunServerError {
            get {
                return ResourceManager.GetString("RunServerError", resourceCulture);
            }
        }
    }
}
