//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSubsystem {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSubsystem.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to allocate disk space, set capacity {0} less than used capacity {1} 的本地化字符串。
        /// </summary>
        internal static string AllocateError {
            get {
                return ResourceManager.GetString("AllocateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not delete system directory 的本地化字符串。
        /// </summary>
        internal static string CanNotDeleteSystemDirectory {
            get {
                return ResourceManager.GetString("CanNotDeleteSystemDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory {0} already exists 的本地化字符串。
        /// </summary>
        internal static string DirectoryExists {
            get {
                return ResourceManager.GetString("DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory {0} does not belong to disk {1} 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotBelongDisk {
            get {
                return ResourceManager.GetString("DirectoryNotBelongDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk root directory 的本地化字符串。
        /// </summary>
        internal static string DiskRootDirectory {
            get {
                return ResourceManager.GetString("DiskRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal disk space, you can use the capacity of less than 0 的本地化字符串。
        /// </summary>
        internal static string DiskSpaceCapacityLessZero {
            get {
                return ResourceManager.GetString("DiskSpaceCapacityLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk space is not enough 的本地化字符串。
        /// </summary>
        internal static string DiskSpaceNotEnough {
            get {
                return ResourceManager.GetString("DiskSpaceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File already exists 的本地化字符串。
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File {0} does not belong to disk {1} 的本地化字符串。
        /// </summary>
        internal static string FileNotBelongDisk {
            get {
                return ResourceManager.GetString("FileNotBelongDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No virtual directory number {0} was found 的本地化字符串。
        /// </summary>
        internal static string NotFoundVirtualDirectory {
            get {
                return ResourceManager.GetString("NotFoundVirtualDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No virtual disk number {0} was found 的本地化字符串。
        /// </summary>
        internal static string NotFoundVirtualDisk {
            get {
                return ResourceManager.GetString("NotFoundVirtualDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No virtual file number {0} was found 的本地化字符串。
        /// </summary>
        internal static string NotFoundVirtualFile {
            get {
                return ResourceManager.GetString("NotFoundVirtualFile", resourceCulture);
            }
        }
    }
}
