//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeArt.Web.XamlControls.Metronic {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeArt.Web.XamlControls.Metronic.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 am 的本地化字符串。
        /// </summary>
        internal static string am {
            get {
                return ResourceManager.GetString("am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apr 的本地化字符串。
        /// </summary>
        internal static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 April 的本地化字符串。
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected item? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least {0} entry {1} 的本地化字符串。
        /// </summary>
        internal static string AtLeastTip {
            get {
                return ResourceManager.GetString("AtLeastTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter at most {0} items {1} 的本地化字符串。
        /// </summary>
        internal static string AtMostTip {
            get {
                return ResourceManager.GetString("AtMostTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aug 的本地化字符串。
        /// </summary>
        internal static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 August 的本地化字符串。
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm password 的本地化字符串。
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Range 的本地化字符串。
        /// </summary>
        internal static string CustomRange {
            get {
                return ResourceManager.GetString("CustomRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DateTitleFormat {
            get {
                return ResourceManager.GetString("DateTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dec 的本地化字符串。
        /// </summary>
        internal static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 December 的本地化字符串。
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deselect All 的本地化字符串。
        /// </summary>
        internal static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel upload 的本地化字符串。
        /// </summary>
        internal static string DictCancelUpload {
            get {
                return ResourceManager.GetString("DictCancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to cancel this upload? 的本地化字符串。
        /// </summary>
        internal static string DictCancelUploadConfirmation {
            get {
                return ResourceManager.GetString("DictCancelUploadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser is not supported 的本地化字符串。
        /// </summary>
        internal static string DictFallbackMessage {
            get {
                return ResourceManager.GetString("DictFallbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload file size cannot exceed {0}M 的本地化字符串。
        /// </summary>
        internal static string DictFileTooBig {
            get {
                return ResourceManager.GetString("DictFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot upload this type of file, the file type can only be {0} 的本地化字符串。
        /// </summary>
        internal static string DictInvalidFileType {
            get {
                return ResourceManager.GetString("DictInvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only upload up to {0} files 的本地化字符串。
        /// </summary>
        internal static string DictMaxFilesExceeded {
            get {
                return ResourceManager.GetString("DictMaxFilesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove file 的本地化字符串。
        /// </summary>
        internal static string DictRemoveFile {
            get {
                return ResourceManager.GetString("DictRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to upload file 的本地化字符串。
        /// </summary>
        internal static string DictResponseError {
            get {
                return ResourceManager.GetString("DictResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displaying {{start}} - {{end}} of {{total}} records 的本地化字符串。
        /// </summary>
        internal static string DisplayingRecords {
            get {
                return ResourceManager.GetString("DisplayingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail format is incorrect 的本地化字符串。
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the confirmation password 的本地化字符串。
        /// </summary>
        internal static string EnterConfirmationPassword {
            get {
                return ResourceManager.GetString("EnterConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter your details to create your account: 的本地化字符串。
        /// </summary>
        internal static string EnterDetailsCreateAccount {
            get {
                return ResourceManager.GetString("EnterDetailsCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please enter your email 的本地化字符串。
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter your email to reset your password: 的本地化字符串。
        /// </summary>
        internal static string EnterEmailResetPassword {
            get {
                return ResourceManager.GetString("EnterEmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the following information 的本地化字符串。
        /// </summary>
        internal static string EnterFollowingInformation {
            get {
                return ResourceManager.GetString("EnterFollowingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the password 的本地化字符串。
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your username 的本地化字符串。
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feb 的本地化字符串。
        /// </summary>
        internal static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 February 的本地化字符串。
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} cannot have more than {1} characters 的本地化字符串。
        /// </summary>
        internal static string FieldMaxLength {
            get {
                return ResourceManager.GetString("FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} cannot have fewer than {1} characters 的本地化字符串。
        /// </summary>
        internal static string FieldMinLength {
            get {
                return ResourceManager.GetString("FieldMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of {0} must be between {1} and {2} 的本地化字符串。
        /// </summary>
        internal static string FieldRange {
            get {
                return ResourceManager.GetString("FieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} required 的本地化字符串。
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill in at least one {0} 的本地化字符串。
        /// </summary>
        internal static string FillLeastOne {
            get {
                return ResourceManager.GetString("FillLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 forget password? 的本地化字符串。
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forgotten Password ? 的本地化字符串。
        /// </summary>
        internal static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fr 的本地化字符串。
        /// </summary>
        internal static string Fr {
            get {
                return ResourceManager.GetString("Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fri 的本地化字符串。
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friday 的本地化字符串。
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jan 的本地化字符串。
        /// </summary>
        internal static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 January 的本地化字符串。
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jul 的本地化字符串。
        /// </summary>
        internal static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 July 的本地化字符串。
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jun 的本地化字符串。
        /// </summary>
        internal static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 June 的本地化字符串。
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 30 Days 的本地化字符串。
        /// </summary>
        internal static string Last30Days {
            get {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 7 Days 的本地化字符串。
        /// </summary>
        internal static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Month 的本地化字符串。
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of {0} must be between {1} and {2} 的本地化字符串。
        /// </summary>
        internal static string ListBetweenNumber {
            get {
                return ResourceManager.GetString("ListBetweenNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more errors occurred for the entry of {0} 的本地化字符串。
        /// </summary>
        internal static string ListItemsError {
            get {
                return ResourceManager.GetString("ListItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mar 的本地化字符串。
        /// </summary>
        internal static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 March 的本地化字符串。
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of {0} options cannot be greater than {1} 的本地化字符串。
        /// </summary>
        internal static string MaxSelectedCountTip {
            get {
                return ResourceManager.GetString("MaxSelectedCountTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 May 的本地化字符串。
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of {0} options cannot be less than {1} 的本地化字符串。
        /// </summary>
        internal static string MinSelectedCountTip {
            get {
                return ResourceManager.GetString("MinSelectedCountTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mo 的本地化字符串。
        /// </summary>
        internal static string Mo {
            get {
                return ResourceManager.GetString("Mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mon 的本地化字符串。
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monday 的本地化字符串。
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More pages 的本地化字符串。
        /// </summary>
        internal static string MorePages {
            get {
                return ResourceManager.GetString("MorePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move down 的本地化字符串。
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move up 的本地化字符串。
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New row 的本地化字符串。
        /// </summary>
        internal static string NewRow {
            get {
                return ResourceManager.GetString("NewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t have an account yet ? 的本地化字符串。
        /// </summary>
        internal static string NoHaveAccount {
            get {
                return ResourceManager.GetString("NoHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No LoadData method set for the DataTable, unable to load the data 的本地化字符串。
        /// </summary>
        internal static string NoLoadDataMethod {
            get {
                return ResourceManager.GetString("NoLoadDataMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No records found 的本地化字符串。
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SignUp method not implemented 的本地化字符串。
        /// </summary>
        internal static string NotImplementedSignUp {
            get {
                return ResourceManager.GetString("NotImplementedSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nov 的本地化字符串。
        /// </summary>
        internal static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 November 的本地化字符串。
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oct 的本地化字符串。
        /// </summary>
        internal static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 October 的本地化字符串。
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only select {0} items 的本地化字符串。
        /// </summary>
        internal static string OnlySelectItems {
            get {
                return ResourceManager.GetString("OnlySelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation succeeded, please login 的本地化字符串。
        /// </summary>
        internal static string OperationSucceededPleaseLogin {
            get {
                return ResourceManager.GetString("OperationSucceededPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page number 的本地化字符串。
        /// </summary>
        internal static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page&apos;s {0} skin not found 的本地化字符串。
        /// </summary>
        internal static string PageSkinNotFound {
            get {
                return ResourceManager.GetString("PageSkinNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid Email 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("PleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select {0} 的本地化字符串。
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait... 的本地化字符串。
        /// </summary>
        internal static string PleaseWaitWithDots {
            get {
                return ResourceManager.GetString("PleaseWaitWithDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pm 的本地化字符串。
        /// </summary>
        internal static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of options for {0} must be between {1} and {2} 的本地化字符串。
        /// </summary>
        internal static string RangeSelectedCount {
            get {
                return ResourceManager.GetString("RangeSelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sa 的本地化字符串。
        /// </summary>
        internal static string Sa {
            get {
                return ResourceManager.GetString("Sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sat 的本地化字符串。
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saturday 的本地化字符串。
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select items to delete 的本地化字符串。
        /// </summary>
        internal static string SelectItemsToDelete {
            get {
                return ResourceManager.GetString("SelectItemsToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select month 的本地化字符串。
        /// </summary>
        internal static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select page size 的本地化字符串。
        /// </summary>
        internal static string SelectPageSize {
            get {
                return ResourceManager.GetString("SelectPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sep 的本地化字符串。
        /// </summary>
        internal static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 September 的本地化字符串。
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcut 的本地化字符串。
        /// </summary>
        internal static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcut group 的本地化字符串。
        /// </summary>
        internal static string ShortcutGroup {
            get {
                return ResourceManager.GetString("ShortcutGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign Up 的本地化字符串。
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Su 的本地化字符串。
        /// </summary>
        internal static string Su {
            get {
                return ResourceManager.GetString("Su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sun 的本地化字符串。
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunday 的本地化字符串。
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System is abnormal 的本地化字符串。
        /// </summary>
        internal static string SystemAbnormal {
            get {
                return ResourceManager.GetString("SystemAbnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Th 的本地化字符串。
        /// </summary>
        internal static string Th {
            get {
                return ResourceManager.GetString("Th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Month 的本地化字符串。
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thu 的本地化字符串。
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thursday 的本地化字符串。
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tu 的本地化字符串。
        /// </summary>
        internal static string Tu {
            get {
                return ResourceManager.GetString("Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tue 的本地化字符串。
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuesday 的本地化字符串。
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password entered twice is different 的本地化字符串。
        /// </summary>
        internal static string TwicePasswordDifferent {
            get {
                return ResourceManager.GetString("TwicePasswordDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop files here or click to upload 的本地化字符串。
        /// </summary>
        internal static string UploadTip {
            get {
                return ResourceManager.GetString("UploadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We 的本地化字符串。
        /// </summary>
        internal static string We {
            get {
                return ResourceManager.GetString("We", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wed 的本地化字符串。
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wednesday 的本地化字符串。
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wrong user name or password 的本地化字符串。
        /// </summary>
        internal static string WrongUserNamePassword {
            get {
                return ResourceManager.GetString("WrongUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday 的本地化字符串。
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
